const appetizers = [
    {
        id: '1',
        name: 'Fry bits',
        price: 4.5,
        image: '../img/1frybits.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '2',
        name: 'Gray Stuff',
        price: 4.5,
        image: '../img/1graystuff.png',
        units: 1,
        allergens: 'Dairy, Gluten, Nuts',
    },
    {
        id: '3',
        name: 'Grubs',
        price: 4.5,
        image: '../img/1grubs.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '4',
        name: 'Rat Soup',
        price: 4.5,
        image: '../img/1ratsoup.png',
        units: 1,
        allergens: 'Dairy, Nuts',
    },
    {
        id: '5',
        name: 'Rice and Bacon',
        price: 4.5,
        image: '../img/1riceandbacon.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '6',
        name: 'Spinach Puffs',
        price: 4.5,
        image: '../img/1spinachpuffs.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
]

const main_dishes = [
    {
        id: '7',
        name: 'Krabby Patty',
        price: 8,
        image: '../img/2krabbypatty.png',
        units: 1,
        allergens: 'Gluten, Nuts',
    },
    {
        id: '8',
        name: 'Spaghetti',
        price: 8,
        image: '../img/2latspaghetti.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '9',
        name: 'Naco',
        price: 8,
        image: '../img/2naco.png',
        units: 1,
        allergens: 'Gluten, Nuts',
    },
    {
        id: '10',
        name: 'Ponyo Ramen',
        price: 8,
        image: '../img/2ponyoramen.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
    {
        id: '11',
        name: 'Popeye Spinach',
        price: 8,
        image: '../img/2popeyespinach.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '12',
        name: 'Scooby Sandwich',
        price: 8,
        image: '../img/2scoobysandwich.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
]

const desserts = [
    {
        id: '13',
        name: 'Alice Cookies',
        price: 5.5,
        image: '../img/3alicecookies.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
    {
        id: '14',
        name: 'Creme De La Creme',
        price: 5.5,
        image: '../img/3cremedelacremealaedgar.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
    {
        id: '15',
        name: 'Hunny',
        price: 5.5,
        image: '../img/3hunny.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '16',
        name: 'Simpsons Donut',
        price: 5.5,
        image: '../img/3simpsonsdonut.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
    {
        id: '17',
        name: 'Together Breakfast',
        price: 5.5,
        image: '../img/3togetherbreakfast.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
    {
        id: '18',
        name: 'Ube Roll',
        price: 5.5,
        image: '../img/3ubecake.png',
        units: 1,
        allergens: 'Dairy, Gluten',
    },
]

const drinks = [
    {
        id: '19',
        name: 'Duff Beer',
        price: 3.75,
        image: '../img/4duffbeer.png',
        units: 1,
        allergens: 'Gluten',
    },
    {
        id: '20',
        name: 'Juggernog',
        price: 3.75,
        image: '../img/4juggernog.png',
        units: 1,
        allergens: 'Dairy, Gluten, Nuts',
    },
    {
        id: '21',
        name: 'Kelpie Shake',
        price: 3.75,
        image: '../img/4kelpshake.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '22',
        name: 'MooMoo Milk',
        price: 3.75,
        image: '../img/4moomoomilk.png',
        units: 1,
        allergens: 'Dairy',
    },
    {
        id: '23',
        name: 'Nuka Cola',
        price: 3.75,
        image: '../img/4nukacola.png',
        units: 1,
        allergens: '&nbsp;',
    },
    {
        id: '24',
        name: 'Skooma',
        price: 3.75,
        image: '../img/4skooma.png',
        units: 1,
        allergens: '&nbsp;',
    },
]
